<a href="https://colab.research.google.com/github/maxF10R35/InteligenciaArtificial/blob/main/neuronas_mcCullock_pits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neurona AND

In [ ]:
#Estructura AND
'''
p  q   pyq  (pw1 + qw2)
0  0    0       0
0  1    0       1
1  0    0       1
1  1    1       2
'''
w1 = 1
w2 = 1
# pyq == 1 si y solo si (pw1 + pw2) == 2

'''
funcion humbral = 0 si (pw1 + pw2) < 2
funcion humbral = 1 si (pw1 + pw2) >= 2
--> humbral = 2

'''
# En resumen

weights = [1,1]
humbral = 2

In [ ]:
# Numpy matrices
import numpy as np

A = np.array([[0,0],[0,1],[1,0],[1,1]])
print(A)

# A es la matríz que contiene todas las posiblescombinaciones de las entradas p, q

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [ ]:
for i in A:
  print(i[1])

0
1
0
1


In [ ]:
class NeuronaAnd:
  def __init__(self,weights,humbral):
    self.weights = weights
    self.humbral = humbral

  def prediccion(self, x):
    for i in x:
      if np.dot(i,self.weights) >= self.humbral:
        print(1)
      else:
        print(0)

In [ ]:
neurona1 = NeuronaAnd(weights,humbral)
neurona1.prediccion(A)


0
0
0
1


# Neurona OR

In [ ]:
# Función OR
'''
si w1 = 1 y w2 = 1
p  q   pyq  (pw1 + pw2)
0  0    0       0
0  1    1       1
1  0    1       1
1  1    1       2

humbral = 1, if (pw1 + pw2) >= 1
humbral = 0, if (pw1 + pw2) < 1
'''
wheights2 = [1,1]
humbral2 = 1

In [ ]:
B = np.array([[0,0],[0,1],[1,0],[1,1]])
print(B)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [ ]:
class NeuronaOr:
  def __init__(self,weights,humbral):
    self.weights = weights
    self.humbral = humbral

  def prediccion(self, x):
    for i in x:
      if np.dot(i,self.weights) >= self.humbral:
        print(1)
      else:
        print(0)

In [ ]:
neurona2 = NeuronaOr(wheights2,humbral2)
neurona2.prediccion(B)

0
1
1
1


# Neurona Implicación p --> q

In [ ]:
# Función implicación
'''
si w1 = 2 y w2 = 1
p  q   p -> q  (pw1 + pw2)
0  0      1       0
0  1      1       1
1  0      0       2
1  1      1       3

humbral = 1, if (pw1 + pw2) >= 1
humbral = 0, if (pw1 + pw2) < 1
'''
wheights3 = [2,1]
humbral3 = 2

In [ ]:
import numpy as np
C = np.array([[0,0],[0,1],[1,0],[1,1]])
print(C)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [ ]:
class Neuronaimp:
  def __init__(self,weights,humbral):
    self.weights = weights
    self.humbral = humbral

  def prediccion(self, x):
    for i in x:
      if np.dot(i,self.weights) == self.humbral:
        print(0)
      else:
        print(1)

In [ ]:
neurona3 = Neuronaimp(wheights3, humbral3)
neurona3.prediccion(C)

1
1
0
1
